version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-management_laravel_app
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    environment:
      - DB_DATABASE=laravel
      - DB_PASSWORD=password

  vite:
    image: node:18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_vite
    working_dir: /var/www/html
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: event-management_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
      - vite
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: event-management_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: event-management_redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: event-management_mailhog
    networks:
      - app-network
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
